### ISSUE TITLE
Problem for reach

### ISSUE THREAD

**Issue by Iwhite67** [BatMen/vetomap#1]
hello

when i go on http://veto.win.white-gaming.fr and create lobby from serv, is working but by external network, is not work

port open
ng serve --host IP

**Comment by Iwhite67** [comment]
WebSocket connection to 'ws://localhost:8999/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by Iwhite67** [comment]
ok, working, i have edit a JS File

**Comment by Iwhite67** [comment]
i work with a  virtual host, my virtual host on veto.white-gaming.fr redirect on dist folder

but with copy link for lobby, is error 404

I don't understand how working

**Comment by BatMen** [comment]
Hello @Iwhite67,

Yes, you need to edit the TypeScript file api.ts to reach your own server. Good job on that.

For the lobby url which gives you a 404 error, it's because your webserver needs to redirect all path to the index.html file. If it's an apache server, you need to add this rules in the virtual host configuration : 

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html[L]
</IfModule>`

**Comment by Iwhite67** [comment]
hum, i thinks if i make this, the url lobby is not reach

**Comment by BatMen** [comment]
When you reach /lobby url, by default, webserver is looking for a "lobby" subfolder in the "dist" folder.

The rules meaning are : 
```
RewriteRule ^index\.html$ - [L] 
```

* stop parsing the rules if the file asked is already "index.html"
```
RewriteCond %{REQUEST_FILENAME} !-f
```

* don't appy the next rule if the URL is targetting an existing file (css and images for example)
```
RewriteCond %{REQUEST_FILENAME} !-d
```

* don't apply the next rule if the URL is targetting an existing folder
```
RewriteRule . /index.html[L]
```

* Redirect all URL suffixes to /index.html file

With this rule set, the "/lobby" url reach the file index.html, which load the Angular application, which know what to do with the "/lobby" route.

This should work.

**Comment by Iwhite67** [comment]
hum

http://veto.white-gaming.fr/lobby/a665bf4b5e766adb64550426f5909dc21a1b148aa068f5f0b00b37c9fea06638e4d650d08edfa2e3f247740577b564848c41eff04490c9bcb88eb332797045d2

With : http://prntscr.com/hoqjcl

**Comment by BatMen** [comment]
You seem to be on a IIS webserver. You may need to use IIS syntax equivalent for rewrite rules

**Comment by Iwhite67** [comment]
http://prntscr.com/hoqlod

**Comment by BatMen** [comment]
It seems that you need to remove the [L] option. IIS imported it like a part of the URL, it's an apache option which means "stop processing next rules if the URL match this rule". It's like the "stop processing" IIS option to true.

**Comment by Iwhite67** [comment]
good ty


<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Imported Rule 1" stopProcessing="true">
                    <match url="^index\.html$" ignoreCase="false" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 2">
                    <match url="." ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/index.html" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>


Merci :) 

Je peut modifier le fichier pour marquer FDJ Open Series ?

**Comment by BatMen** [comment]
To be honest, I don't even understand my own LICENSE file FeelsBadMan. If you can add credits somewhere  to my mapveto project, I would appreciate it ;) If not, no big deal, I won't sue you ^^
